### PR TITLE
Added a new workflow step that can concatenate a field from child records

### PR DESCRIPTION
**Pull request by rajrao**
Added a workflow that will allow one to define a fetchXml query and use the field to perform a concatenation using the data from all the records.

Account has a field ContactsList which needs the names of all child Contacts to be shown.

### CODE REVIEW

**Comment by rajrao** [comment]
I saw that you were using "Microsoft.Crm.Sdk.Proxy.dll" from a custom folder outside of the actual solution path. I copied the latest Microsoft.Crm.Sdk.Proxy.dll into the packages folder in the hopes that at some point a new updated package will be provided by CrmSdk. If you want me to provide an updated pull request using your original path, I can do that.

I added documentation files, so hopefully that will tell you what this workflow step does.

**Comment by rajrao** [comment]
Hi @demianrasko wondering what you think about this PR

**Comment by miklemiracle** [comment]
Hi, @rajrao!

Can we try your WF step as per beta-testers? We have couple of such tasks, and we use plug-ins as a solution :(

**Comment by rajrao** [comment]
Hi @miklemiracle, not sure i understand. If you want to use this code in a plugin, you can go ahead and do so. otherwise send me more info and I can fix the code if it will help you complete the pull-request.

**Pull request merged**
